<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.wang.light</groupId>
        <artifactId>light-api-tester</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>light-api-report</artifactId>
    <name>light-api-report</name>
    <description>Allure integration (optional dep) + test platform publisher</description>

    <dependencies>
        <dependency>
            <groupId>com.wang.light</groupId>
            <artifactId>light-api-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
